plugins { id 'com.android.application' }

android {
    namespace 'com.kplay.horseracing.gumvit'
    compileSdk 35

    defaultConfig {
        applicationId 'com.kplay.horseracing.crosspool'
        minSdk 23
        targetSdk 35
        versionCode 20
        versionName '2.0.0'
    }
}

dependencies {
    implementation 'org.jsoup:jsoup:1.18.3'
}
