package com.kplay.horseracing.gumvit;
import android.content.*;import android.net.Uri;import org.json.*;import java.io.*;import java.time.*;import java.util.concurrent.atomic.AtomicBoolean;
final class HistCollectorService{
 static final String[] TRACKS={"SEOUL","BUSAN_GYEONGNAM","JEJU","YEONGCHEON"};final Context ctx;final HistCollectorStore db;final AtomicBoolean running=new AtomicBoolean(false),stop=new AtomicBoolean(false);volatile String state="IDLE",message="";
 HistCollectorService(Context c){ctx=c.getApplicationContext();db=new HistCollectorStore(ctx);}
 JSONObject status(){try{return new JSONObject().put("ok",true).put("state",state).put("message",message).put("running",running.get()).put("raceCount",db.count("race")).put("runnerCount",db.count("runner")).put("oddsCount",db.count("odds"));}catch(Exception e){return err(e);}}
 JSONObject start(Runnable changed){if(!running.compareAndSet(false,true))return status();stop.set(false);state="COLLECTING";new Thread(()->{try{LocalDate end=LocalDate.now(),fallback=end.minusYears(5);for(String t:TRACKS){LocalDate begin=db.resume(t,fallback);for(LocalDate d=begin;!d.isAfter(end)&&!stop.get();d=d.plusDays(1)){if(!HistKraHistorySource.validTrackDate(t,d)){db.checkpoint(t,d.plusDays(1));continue;}boolean failed=false;for(int r=1;r<=16&&!stop.get();r++){try{HistKraHistorySource.Race x=HistKraHistorySource.fetch(t,d,r);if(x==null)break;db.save(x);message=t+" "+d+" R"+r;changed.run();Thread.sleep(250);}catch(Exception e){failed=true;message=t+" "+d+" 오류 · 저장분 유지: "+e.getClass().getSimpleName();changed.run();break;}}if(failed||stop.get())break;db.checkpoint(t,d.plusDays(1));}}state=stop.get()?"STOPPED":"COLLECTED";}catch(Exception e){state="FAILED_SKIPPED";message=String.valueOf(e.getMessage());}finally{db.flush();running.set(false);changed.run();}},"PEGASUS-HIST-COLLECT").start();return status();}
 JSONObject stop(){stop.set(true);state="STOP_REQUESTED";return status();}
 JSONObject installToPegasus(HistRepository repo)throws Exception{if(running.get())return new JSONObject().put("ok",false).put("error","수집 중에는 설치할 수 없습니다.");db.flush();File src=ctx.getDatabasePath(HistCollectorStore.DB);if(!src.exists())return new JSONObject().put("ok",false).put("error","수집 DB 없음");return repo.importFrom(Uri.fromFile(src));}
 private JSONObject err(Exception e){try{return new JSONObject().put("ok",false).put("state","FAILED_SKIPPED").put("error",String.valueOf(e.getMessage()));}catch(Exception x){return new JSONObject();}}
}